### ISSUE TITLE
Döküman nerde ?

### ISSUE THREAD

**Issue by frknbasaran** [ozziest/mavidurak-blog-chrome-extension#1]
Sevgili Özgür Adem

Dökümantasyonu nerede bunun? Ya paketlenmemiş eklenti kurmayı bilmiyorsak? Biraz dikkate davet ediyorum sizi.

Efendi olun, adam olun lan.

**Comment by okan** [comment]
@frknbasaran @ozziest Mağaza üzerinde neden yayına almıyoruz bunu?

**Comment by ozziest** [comment]
@frknbasaran doküman ilk fırsatta hazırlanacak. Emin olabilirsin. ;)
@okanvurdu mağazada yayınlamak için para ödememiz gerekiyormuş. Biz fakir insanlarız. :)

**Comment by frknbasaran** [comment]
siz fakirsiniz ama ben değilim, dur yayınlayayım da az sevap point kasayım.

**Comment by frknbasaran** [comment]
(döküman hazırlanmadı)

**Comment by frknbasaran** [comment]
https://chrome.google.com/webstore/detail/jpjmcmmnmfhpppojggnbdidphdlghcah/publish-delayed?hl=tr

**Comment by ozziest** [comment]
Link geçersiz.
